### ISSUE TITLE
more-like-this filter in demo

### ISSUE THREAD

**Issue by dmackinn** [lnx-search/lnx-cli#1]
lnx-cli version: 0.9.0
lnx version: 0.9.0 (via docker)
rustc version: 1.63.0

Does the more-like-this filter when running demo currently do anything? Switching between fuzzy and normal matching changes results as expected but attempting to search terms with more-like-this does not seem to alter the results at all.

**Comment by ChillFish8** [comment]
the `more-like-this` query is for matching similar documents to a given document. So the demo expects that you give it a document_id and it will then produce documents similar to that document. Rather than being a keyword search as such.

**Comment by dmackinn** [comment]
Thanks for the details and quick response! That makes sense. One more question, any insight into why American Psycho II matched under "more like this" to Avengers:Age of Ultron in the demo data set?

**Comment by ChillFish8** [comment]
It's largely down to the algorithm and the default settings. It may be that the demo docs (which indexes the description) contain many of the same or similar terms.

Saying that you can in an actual implementation, tweak the parameters as part of an actual request.

**Comment by dmackinn** [comment]
I took a look at the index payload in the demo lib and see what you mean. Thanks!
